// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/admin/cart_admin_service.proto

package admin

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// CartAdminServiceClient is the client API for CartAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CartAdminServiceClient interface {
}

type cartAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCartAdminServiceClient(cc grpc.ClientConnInterface) CartAdminServiceClient {
	return &cartAdminServiceClient{cc}
}

// CartAdminServiceServer is the server API for CartAdminService service.
// All implementations must embed UnimplementedCartAdminServiceServer
// for forward compatibility.
type CartAdminServiceServer interface {
	mustEmbedUnimplementedCartAdminServiceServer()
}

// UnimplementedCartAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCartAdminServiceServer struct{}

func (UnimplementedCartAdminServiceServer) mustEmbedUnimplementedCartAdminServiceServer() {}
func (UnimplementedCartAdminServiceServer) testEmbeddedByValue()                          {}

// UnsafeCartAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CartAdminServiceServer will
// result in compilation errors.
type UnsafeCartAdminServiceServer interface {
	mustEmbedUnimplementedCartAdminServiceServer()
}

func RegisterCartAdminServiceServer(s grpc.ServiceRegistrar, srv CartAdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedCartAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CartAdminService_ServiceDesc, srv)
}

// CartAdminService_ServiceDesc is the grpc.ServiceDesc for CartAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CartAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.martketplace.vkr.cart.pkg.api.grpc.v1.admin.CartAdminService",
	HandlerType: (*CartAdminServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "v1/admin/cart_admin_service.proto",
}
