// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/order/cart_order_service.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckoutReservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckoutId    string                 `protobuf:"bytes,1,opt,name=checkout_id,json=checkoutId,proto3" json:"checkout_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*CheckoutCartItem    `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Totals        *CheckoutCartTotals    `protobuf:"bytes,4,opt,name=totals,proto3" json:"totals,omitempty"`
	CartVersion   uint64                 `protobuf:"varint,5,opt,name=cart_version,json=cartVersion,proto3" json:"cart_version,omitempty"`
	ReservedUntil *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=reserved_until,json=reservedUntil,proto3" json:"reserved_until,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutReservation) Reset() {
	*x = CheckoutReservation{}
	mi := &file_v1_order_cart_order_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutReservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutReservation) ProtoMessage() {}

func (x *CheckoutReservation) ProtoReflect() protoreflect.Message {
	mi := &file_v1_order_cart_order_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutReservation.ProtoReflect.Descriptor instead.
func (*CheckoutReservation) Descriptor() ([]byte, []int) {
	return file_v1_order_cart_order_service_proto_rawDescGZIP(), []int{0}
}

func (x *CheckoutReservation) GetCheckoutId() string {
	if x != nil {
		return x.CheckoutId
	}
	return ""
}

func (x *CheckoutReservation) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckoutReservation) GetItems() []*CheckoutCartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CheckoutReservation) GetTotals() *CheckoutCartTotals {
	if x != nil {
		return x.Totals
	}
	return nil
}

func (x *CheckoutReservation) GetCartVersion() uint64 {
	if x != nil {
		return x.CartVersion
	}
	return 0
}

func (x *CheckoutReservation) GetReservedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ReservedUntil
	}
	return nil
}

func (x *CheckoutReservation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CheckoutCartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VendorId      int64                  `protobuf:"varint,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	VendorName    string                 `protobuf:"bytes,3,opt,name=vendor_name,json=vendorName,proto3" json:"vendor_name,omitempty"`
	ProductName   string                 `protobuf:"bytes,4,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Quantity      uint32                 `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     string                 `protobuf:"bytes,7,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	TotalPrice    string                 `protobuf:"bytes,8,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	CurrencyId    int64                  `protobuf:"varint,9,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	RubPrice      string                 `protobuf:"bytes,10,opt,name=rub_price,json=rubPrice,proto3" json:"rub_price,omitempty"`
	UsdtPrice     string                 `protobuf:"bytes,11,opt,name=usdt_price,json=usdtPrice,proto3" json:"usdt_price,omitempty"`
	RubPerUsdt    string                 `protobuf:"bytes,12,opt,name=rub_per_usdt,json=rubPerUsdt,proto3" json:"rub_per_usdt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutCartItem) Reset() {
	*x = CheckoutCartItem{}
	mi := &file_v1_order_cart_order_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutCartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutCartItem) ProtoMessage() {}

func (x *CheckoutCartItem) ProtoReflect() protoreflect.Message {
	mi := &file_v1_order_cart_order_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutCartItem.ProtoReflect.Descriptor instead.
func (*CheckoutCartItem) Descriptor() ([]byte, []int) {
	return file_v1_order_cart_order_service_proto_rawDescGZIP(), []int{1}
}

func (x *CheckoutCartItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CheckoutCartItem) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *CheckoutCartItem) GetVendorName() string {
	if x != nil {
		return x.VendorName
	}
	return ""
}

func (x *CheckoutCartItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *CheckoutCartItem) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CheckoutCartItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CheckoutCartItem) GetUnitPrice() string {
	if x != nil {
		return x.UnitPrice
	}
	return ""
}

func (x *CheckoutCartItem) GetTotalPrice() string {
	if x != nil {
		return x.TotalPrice
	}
	return ""
}

func (x *CheckoutCartItem) GetCurrencyId() int64 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *CheckoutCartItem) GetRubPrice() string {
	if x != nil {
		return x.RubPrice
	}
	return ""
}

func (x *CheckoutCartItem) GetUsdtPrice() string {
	if x != nil {
		return x.UsdtPrice
	}
	return ""
}

func (x *CheckoutCartItem) GetRubPerUsdt() string {
	if x != nil {
		return x.RubPerUsdt
	}
	return ""
}

type CheckoutCartTotals struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalItems    uint32                 `protobuf:"varint,1,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	Subtotal      string                 `protobuf:"bytes,2,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	Discount      string                 `protobuf:"bytes,3,opt,name=discount,proto3" json:"discount,omitempty"`
	Total         string                 `protobuf:"bytes,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutCartTotals) Reset() {
	*x = CheckoutCartTotals{}
	mi := &file_v1_order_cart_order_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutCartTotals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutCartTotals) ProtoMessage() {}

func (x *CheckoutCartTotals) ProtoReflect() protoreflect.Message {
	mi := &file_v1_order_cart_order_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutCartTotals.ProtoReflect.Descriptor instead.
func (*CheckoutCartTotals) Descriptor() ([]byte, []int) {
	return file_v1_order_cart_order_service_proto_rawDescGZIP(), []int{2}
}

func (x *CheckoutCartTotals) GetTotalItems() uint32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *CheckoutCartTotals) GetSubtotal() string {
	if x != nil {
		return x.Subtotal
	}
	return ""
}

func (x *CheckoutCartTotals) GetDiscount() string {
	if x != nil {
		return x.Discount
	}
	return ""
}

func (x *CheckoutCartTotals) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

type ReserveCheckoutItemsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserId              int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CheckoutId          string                 `protobuf:"bytes,2,opt,name=checkout_id,json=checkoutId,proto3" json:"checkout_id,omitempty"`
	ProductIds          []int64                `protobuf:"varint,3,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	ExpectedCartVersion uint64                 `protobuf:"varint,4,opt,name=expected_cart_version,json=expectedCartVersion,proto3" json:"expected_cart_version,omitempty"`
	PreferredCurrencyId int64                  `protobuf:"varint,5,opt,name=preferred_currency_id,json=preferredCurrencyId,proto3" json:"preferred_currency_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReserveCheckoutItemsRequest) Reset() {
	*x = ReserveCheckoutItemsRequest{}
	mi := &file_v1_order_cart_order_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveCheckoutItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveCheckoutItemsRequest) ProtoMessage() {}

func (x *ReserveCheckoutItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_order_cart_order_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveCheckoutItemsRequest.ProtoReflect.Descriptor instead.
func (*ReserveCheckoutItemsRequest) Descriptor() ([]byte, []int) {
	return file_v1_order_cart_order_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReserveCheckoutItemsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReserveCheckoutItemsRequest) GetCheckoutId() string {
	if x != nil {
		return x.CheckoutId
	}
	return ""
}

func (x *ReserveCheckoutItemsRequest) GetProductIds() []int64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *ReserveCheckoutItemsRequest) GetExpectedCartVersion() uint64 {
	if x != nil {
		return x.ExpectedCartVersion
	}
	return 0
}

func (x *ReserveCheckoutItemsRequest) GetPreferredCurrencyId() int64 {
	if x != nil {
		return x.PreferredCurrencyId
	}
	return 0
}

type ReserveCheckoutItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   *CheckoutReservation   `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveCheckoutItemsResponse) Reset() {
	*x = ReserveCheckoutItemsResponse{}
	mi := &file_v1_order_cart_order_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveCheckoutItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveCheckoutItemsResponse) ProtoMessage() {}

func (x *ReserveCheckoutItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_order_cart_order_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveCheckoutItemsResponse.ProtoReflect.Descriptor instead.
func (*ReserveCheckoutItemsResponse) Descriptor() ([]byte, []int) {
	return file_v1_order_cart_order_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveCheckoutItemsResponse) GetReservation() *CheckoutReservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

type GetCheckoutReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CheckoutId    string                 `protobuf:"bytes,2,opt,name=checkout_id,json=checkoutId,proto3" json:"checkout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckoutReservationRequest) Reset() {
	*x = GetCheckoutReservationRequest{}
	mi := &file_v1_order_cart_order_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckoutReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckoutReservationRequest) ProtoMessage() {}

func (x *GetCheckoutReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_order_cart_order_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckoutReservationRequest.ProtoReflect.Descriptor instead.
func (*GetCheckoutReservationRequest) Descriptor() ([]byte, []int) {
	return file_v1_order_cart_order_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetCheckoutReservationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetCheckoutReservationRequest) GetCheckoutId() string {
	if x != nil {
		return x.CheckoutId
	}
	return ""
}

type GetCheckoutReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   *CheckoutReservation   `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckoutReservationResponse) Reset() {
	*x = GetCheckoutReservationResponse{}
	mi := &file_v1_order_cart_order_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckoutReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckoutReservationResponse) ProtoMessage() {}

func (x *GetCheckoutReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_order_cart_order_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckoutReservationResponse.ProtoReflect.Descriptor instead.
func (*GetCheckoutReservationResponse) Descriptor() ([]byte, []int) {
	return file_v1_order_cart_order_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetCheckoutReservationResponse) GetReservation() *CheckoutReservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

type CommitCheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CheckoutId    string                 `protobuf:"bytes,2,opt,name=checkout_id,json=checkoutId,proto3" json:"checkout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitCheckoutRequest) Reset() {
	*x = CommitCheckoutRequest{}
	mi := &file_v1_order_cart_order_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitCheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitCheckoutRequest) ProtoMessage() {}

func (x *CommitCheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_order_cart_order_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitCheckoutRequest.ProtoReflect.Descriptor instead.
func (*CommitCheckoutRequest) Descriptor() ([]byte, []int) {
	return file_v1_order_cart_order_service_proto_rawDescGZIP(), []int{7}
}

func (x *CommitCheckoutRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommitCheckoutRequest) GetCheckoutId() string {
	if x != nil {
		return x.CheckoutId
	}
	return ""
}

type CommitCheckoutResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CheckoutId        string                 `protobuf:"bytes,2,opt,name=checkout_id,json=checkoutId,proto3" json:"checkout_id,omitempty"`
	RemovedProductIds []int64                `protobuf:"varint,3,rep,packed,name=removed_product_ids,json=removedProductIds,proto3" json:"removed_product_ids,omitempty"`
	CartVersion       uint64                 `protobuf:"varint,4,opt,name=cart_version,json=cartVersion,proto3" json:"cart_version,omitempty"`
	CommittedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=committed_at,json=committedAt,proto3" json:"committed_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CommitCheckoutResponse) Reset() {
	*x = CommitCheckoutResponse{}
	mi := &file_v1_order_cart_order_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitCheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitCheckoutResponse) ProtoMessage() {}

func (x *CommitCheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_order_cart_order_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitCheckoutResponse.ProtoReflect.Descriptor instead.
func (*CommitCheckoutResponse) Descriptor() ([]byte, []int) {
	return file_v1_order_cart_order_service_proto_rawDescGZIP(), []int{8}
}

func (x *CommitCheckoutResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CommitCheckoutResponse) GetCheckoutId() string {
	if x != nil {
		return x.CheckoutId
	}
	return ""
}

func (x *CommitCheckoutResponse) GetRemovedProductIds() []int64 {
	if x != nil {
		return x.RemovedProductIds
	}
	return nil
}

func (x *CommitCheckoutResponse) GetCartVersion() uint64 {
	if x != nil {
		return x.CartVersion
	}
	return 0
}

func (x *CommitCheckoutResponse) GetCommittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CommittedAt
	}
	return nil
}

type ReleaseCheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CheckoutId    string                 `protobuf:"bytes,2,opt,name=checkout_id,json=checkoutId,proto3" json:"checkout_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseCheckoutRequest) Reset() {
	*x = ReleaseCheckoutRequest{}
	mi := &file_v1_order_cart_order_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCheckoutRequest) ProtoMessage() {}

func (x *ReleaseCheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_order_cart_order_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCheckoutRequest.ProtoReflect.Descriptor instead.
func (*ReleaseCheckoutRequest) Descriptor() ([]byte, []int) {
	return file_v1_order_cart_order_service_proto_rawDescGZIP(), []int{9}
}

func (x *ReleaseCheckoutRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReleaseCheckoutRequest) GetCheckoutId() string {
	if x != nil {
		return x.CheckoutId
	}
	return ""
}

func (x *ReleaseCheckoutRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReleaseCheckoutResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CheckoutId         string                 `protobuf:"bytes,2,opt,name=checkout_id,json=checkoutId,proto3" json:"checkout_id,omitempty"`
	ReleasedProductIds []int64                `protobuf:"varint,3,rep,packed,name=released_product_ids,json=releasedProductIds,proto3" json:"released_product_ids,omitempty"`
	CartVersion        uint64                 `protobuf:"varint,4,opt,name=cart_version,json=cartVersion,proto3" json:"cart_version,omitempty"`
	ReleasedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=released_at,json=releasedAt,proto3" json:"released_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReleaseCheckoutResponse) Reset() {
	*x = ReleaseCheckoutResponse{}
	mi := &file_v1_order_cart_order_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCheckoutResponse) ProtoMessage() {}

func (x *ReleaseCheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_order_cart_order_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCheckoutResponse.ProtoReflect.Descriptor instead.
func (*ReleaseCheckoutResponse) Descriptor() ([]byte, []int) {
	return file_v1_order_cart_order_service_proto_rawDescGZIP(), []int{10}
}

func (x *ReleaseCheckoutResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReleaseCheckoutResponse) GetCheckoutId() string {
	if x != nil {
		return x.CheckoutId
	}
	return ""
}

func (x *ReleaseCheckoutResponse) GetReleasedProductIds() []int64 {
	if x != nil {
		return x.ReleasedProductIds
	}
	return nil
}

func (x *ReleaseCheckoutResponse) GetCartVersion() uint64 {
	if x != nil {
		return x.CartVersion
	}
	return 0
}

func (x *ReleaseCheckoutResponse) GetReleasedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReleasedAt
	}
	return nil
}

var File_v1_order_cart_order_service_proto protoreflect.FileDescriptor

const file_v1_order_cart_order_service_proto_rawDesc = "" +
	"\n" +
	"!v1/order/cart_order_service.proto\x126github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x03\n" +
	"\x13CheckoutReservation\x12\x1f\n" +
	"\vcheckout_id\x18\x01 \x01(\tR\n" +
	"checkoutId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12^\n" +
	"\x05items\x18\x03 \x03(\v2H.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CheckoutCartItemR\x05items\x12b\n" +
	"\x06totals\x18\x04 \x01(\v2J.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CheckoutCartTotalsR\x06totals\x12!\n" +
	"\fcart_version\x18\x05 \x01(\x04R\vcartVersion\x12A\n" +
	"\x0ereserved_until\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rreservedUntil\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8a\x03\n" +
	"\x10CheckoutCartItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1b\n" +
	"\tvendor_id\x18\x02 \x01(\x03R\bvendorId\x12\x1f\n" +
	"\vvendor_name\x18\x03 \x01(\tR\n" +
	"vendorName\x12!\n" +
	"\fproduct_name\x18\x04 \x01(\tR\vproductName\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\rR\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\a \x01(\tR\tunitPrice\x12\x1f\n" +
	"\vtotal_price\x18\b \x01(\tR\n" +
	"totalPrice\x12\x1f\n" +
	"\vcurrency_id\x18\t \x01(\x03R\n" +
	"currencyId\x12\x1b\n" +
	"\trub_price\x18\n" +
	" \x01(\tR\brubPrice\x12\x1d\n" +
	"\n" +
	"usdt_price\x18\v \x01(\tR\tusdtPrice\x12 \n" +
	"\frub_per_usdt\x18\f \x01(\tR\n" +
	"rubPerUsdt\"\x83\x01\n" +
	"\x12CheckoutCartTotals\x12\x1f\n" +
	"\vtotal_items\x18\x01 \x01(\rR\n" +
	"totalItems\x12\x1a\n" +
	"\bsubtotal\x18\x02 \x01(\tR\bsubtotal\x12\x1a\n" +
	"\bdiscount\x18\x03 \x01(\tR\bdiscount\x12\x14\n" +
	"\x05total\x18\x04 \x01(\tR\x05total\"\xe0\x01\n" +
	"\x1bReserveCheckoutItemsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vcheckout_id\x18\x02 \x01(\tR\n" +
	"checkoutId\x12\x1f\n" +
	"\vproduct_ids\x18\x03 \x03(\x03R\n" +
	"productIds\x122\n" +
	"\x15expected_cart_version\x18\x04 \x01(\x04R\x13expectedCartVersion\x122\n" +
	"\x15preferred_currency_id\x18\x05 \x01(\x03R\x13preferredCurrencyId\"\x8d\x01\n" +
	"\x1cReserveCheckoutItemsResponse\x12m\n" +
	"\vreservation\x18\x01 \x01(\v2K.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CheckoutReservationR\vreservation\"Y\n" +
	"\x1dGetCheckoutReservationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vcheckout_id\x18\x02 \x01(\tR\n" +
	"checkoutId\"\x8f\x01\n" +
	"\x1eGetCheckoutReservationResponse\x12m\n" +
	"\vreservation\x18\x01 \x01(\v2K.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CheckoutReservationR\vreservation\"Q\n" +
	"\x15CommitCheckoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vcheckout_id\x18\x02 \x01(\tR\n" +
	"checkoutId\"\xe4\x01\n" +
	"\x16CommitCheckoutResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vcheckout_id\x18\x02 \x01(\tR\n" +
	"checkoutId\x12.\n" +
	"\x13removed_product_ids\x18\x03 \x03(\x03R\x11removedProductIds\x12!\n" +
	"\fcart_version\x18\x04 \x01(\x04R\vcartVersion\x12=\n" +
	"\fcommitted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcommittedAt\"j\n" +
	"\x16ReleaseCheckoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vcheckout_id\x18\x02 \x01(\tR\n" +
	"checkoutId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xe5\x01\n" +
	"\x17ReleaseCheckoutResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vcheckout_id\x18\x02 \x01(\tR\n" +
	"checkoutId\x120\n" +
	"\x14released_product_ids\x18\x03 \x03(\x03R\x12releasedProductIds\x12!\n" +
	"\fcart_version\x18\x04 \x01(\x04R\vcartVersion\x12;\n" +
	"\vreleased_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"releasedAt2\x87\x06\n" +
	"\x10CartOrderService\x12\xc1\x01\n" +
	"\x14ReserveCheckoutItems\x12S.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.ReserveCheckoutItemsRequest\x1aT.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.ReserveCheckoutItemsResponse\x12\xc7\x01\n" +
	"\x16GetCheckoutReservation\x12U.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.GetCheckoutReservationRequest\x1aV.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.GetCheckoutReservationResponse\x12\xaf\x01\n" +
	"\x0eCommitCheckout\x12M.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CommitCheckoutRequest\x1aN.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CommitCheckoutResponse\x12\xb2\x01\n" +
	"\x0fReleaseCheckout\x12N.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.ReleaseCheckoutRequest\x1aO.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.ReleaseCheckoutResponseB>Z<github.com/martketplace-vkr/cart/pkg/api/grpc/v1/order;orderb\x06proto3"

var (
	file_v1_order_cart_order_service_proto_rawDescOnce sync.Once
	file_v1_order_cart_order_service_proto_rawDescData []byte
)

func file_v1_order_cart_order_service_proto_rawDescGZIP() []byte {
	file_v1_order_cart_order_service_proto_rawDescOnce.Do(func() {
		file_v1_order_cart_order_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_order_cart_order_service_proto_rawDesc), len(file_v1_order_cart_order_service_proto_rawDesc)))
	})
	return file_v1_order_cart_order_service_proto_rawDescData
}

var file_v1_order_cart_order_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_v1_order_cart_order_service_proto_goTypes = []any{
	(*CheckoutReservation)(nil),            // 0: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CheckoutReservation
	(*CheckoutCartItem)(nil),               // 1: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CheckoutCartItem
	(*CheckoutCartTotals)(nil),             // 2: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CheckoutCartTotals
	(*ReserveCheckoutItemsRequest)(nil),    // 3: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.ReserveCheckoutItemsRequest
	(*ReserveCheckoutItemsResponse)(nil),   // 4: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.ReserveCheckoutItemsResponse
	(*GetCheckoutReservationRequest)(nil),  // 5: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.GetCheckoutReservationRequest
	(*GetCheckoutReservationResponse)(nil), // 6: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.GetCheckoutReservationResponse
	(*CommitCheckoutRequest)(nil),          // 7: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CommitCheckoutRequest
	(*CommitCheckoutResponse)(nil),         // 8: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CommitCheckoutResponse
	(*ReleaseCheckoutRequest)(nil),         // 9: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.ReleaseCheckoutRequest
	(*ReleaseCheckoutResponse)(nil),        // 10: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.ReleaseCheckoutResponse
	(*timestamppb.Timestamp)(nil),          // 11: google.protobuf.Timestamp
}
var file_v1_order_cart_order_service_proto_depIdxs = []int32{
	1,  // 0: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CheckoutReservation.items:type_name -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CheckoutCartItem
	2,  // 1: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CheckoutReservation.totals:type_name -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CheckoutCartTotals
	11, // 2: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CheckoutReservation.reserved_until:type_name -> google.protobuf.Timestamp
	11, // 3: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CheckoutReservation.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.ReserveCheckoutItemsResponse.reservation:type_name -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CheckoutReservation
	0,  // 5: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.GetCheckoutReservationResponse.reservation:type_name -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CheckoutReservation
	11, // 6: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CommitCheckoutResponse.committed_at:type_name -> google.protobuf.Timestamp
	11, // 7: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.ReleaseCheckoutResponse.released_at:type_name -> google.protobuf.Timestamp
	3,  // 8: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CartOrderService.ReserveCheckoutItems:input_type -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.ReserveCheckoutItemsRequest
	5,  // 9: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CartOrderService.GetCheckoutReservation:input_type -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.GetCheckoutReservationRequest
	7,  // 10: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CartOrderService.CommitCheckout:input_type -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CommitCheckoutRequest
	9,  // 11: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CartOrderService.ReleaseCheckout:input_type -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.ReleaseCheckoutRequest
	4,  // 12: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CartOrderService.ReserveCheckoutItems:output_type -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.ReserveCheckoutItemsResponse
	6,  // 13: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CartOrderService.GetCheckoutReservation:output_type -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.GetCheckoutReservationResponse
	8,  // 14: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CartOrderService.CommitCheckout:output_type -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CommitCheckoutResponse
	10, // 15: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CartOrderService.ReleaseCheckout:output_type -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.ReleaseCheckoutResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_v1_order_cart_order_service_proto_init() }
func file_v1_order_cart_order_service_proto_init() {
	if File_v1_order_cart_order_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_order_cart_order_service_proto_rawDesc), len(file_v1_order_cart_order_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_order_cart_order_service_proto_goTypes,
		DependencyIndexes: file_v1_order_cart_order_service_proto_depIdxs,
		MessageInfos:      file_v1_order_cart_order_service_proto_msgTypes,
	}.Build()
	File_v1_order_cart_order_service_proto = out.File
	file_v1_order_cart_order_service_proto_goTypes = nil
	file_v1_order_cart_order_service_proto_depIdxs = nil
}
