// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: v1/order/cart_order_service.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CartOrderService_ReserveCheckoutItems_FullMethodName   = "/github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CartOrderService/ReserveCheckoutItems"
	CartOrderService_GetCheckoutReservation_FullMethodName = "/github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CartOrderService/GetCheckoutReservation"
	CartOrderService_CommitCheckout_FullMethodName         = "/github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CartOrderService/CommitCheckout"
	CartOrderService_ReleaseCheckout_FullMethodName        = "/github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CartOrderService/ReleaseCheckout"
)

// CartOrderServiceClient is the client API for CartOrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CartOrderServiceClient interface {
	ReserveCheckoutItems(ctx context.Context, in *ReserveCheckoutItemsRequest, opts ...grpc.CallOption) (*ReserveCheckoutItemsResponse, error)
	GetCheckoutReservation(ctx context.Context, in *GetCheckoutReservationRequest, opts ...grpc.CallOption) (*GetCheckoutReservationResponse, error)
	CommitCheckout(ctx context.Context, in *CommitCheckoutRequest, opts ...grpc.CallOption) (*CommitCheckoutResponse, error)
	ReleaseCheckout(ctx context.Context, in *ReleaseCheckoutRequest, opts ...grpc.CallOption) (*ReleaseCheckoutResponse, error)
}

type cartOrderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCartOrderServiceClient(cc grpc.ClientConnInterface) CartOrderServiceClient {
	return &cartOrderServiceClient{cc}
}

func (c *cartOrderServiceClient) ReserveCheckoutItems(ctx context.Context, in *ReserveCheckoutItemsRequest, opts ...grpc.CallOption) (*ReserveCheckoutItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveCheckoutItemsResponse)
	err := c.cc.Invoke(ctx, CartOrderService_ReserveCheckoutItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartOrderServiceClient) GetCheckoutReservation(ctx context.Context, in *GetCheckoutReservationRequest, opts ...grpc.CallOption) (*GetCheckoutReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCheckoutReservationResponse)
	err := c.cc.Invoke(ctx, CartOrderService_GetCheckoutReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartOrderServiceClient) CommitCheckout(ctx context.Context, in *CommitCheckoutRequest, opts ...grpc.CallOption) (*CommitCheckoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitCheckoutResponse)
	err := c.cc.Invoke(ctx, CartOrderService_CommitCheckout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartOrderServiceClient) ReleaseCheckout(ctx context.Context, in *ReleaseCheckoutRequest, opts ...grpc.CallOption) (*ReleaseCheckoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseCheckoutResponse)
	err := c.cc.Invoke(ctx, CartOrderService_ReleaseCheckout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartOrderServiceServer is the server API for CartOrderService service.
// All implementations must embed UnimplementedCartOrderServiceServer
// for forward compatibility.
type CartOrderServiceServer interface {
	ReserveCheckoutItems(context.Context, *ReserveCheckoutItemsRequest) (*ReserveCheckoutItemsResponse, error)
	GetCheckoutReservation(context.Context, *GetCheckoutReservationRequest) (*GetCheckoutReservationResponse, error)
	CommitCheckout(context.Context, *CommitCheckoutRequest) (*CommitCheckoutResponse, error)
	ReleaseCheckout(context.Context, *ReleaseCheckoutRequest) (*ReleaseCheckoutResponse, error)
	mustEmbedUnimplementedCartOrderServiceServer()
}

// UnimplementedCartOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCartOrderServiceServer struct{}

func (UnimplementedCartOrderServiceServer) ReserveCheckoutItems(context.Context, *ReserveCheckoutItemsRequest) (*ReserveCheckoutItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReserveCheckoutItems not implemented")
}
func (UnimplementedCartOrderServiceServer) GetCheckoutReservation(context.Context, *GetCheckoutReservationRequest) (*GetCheckoutReservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCheckoutReservation not implemented")
}
func (UnimplementedCartOrderServiceServer) CommitCheckout(context.Context, *CommitCheckoutRequest) (*CommitCheckoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitCheckout not implemented")
}
func (UnimplementedCartOrderServiceServer) ReleaseCheckout(context.Context, *ReleaseCheckoutRequest) (*ReleaseCheckoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseCheckout not implemented")
}
func (UnimplementedCartOrderServiceServer) mustEmbedUnimplementedCartOrderServiceServer() {}
func (UnimplementedCartOrderServiceServer) testEmbeddedByValue()                          {}

// UnsafeCartOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CartOrderServiceServer will
// result in compilation errors.
type UnsafeCartOrderServiceServer interface {
	mustEmbedUnimplementedCartOrderServiceServer()
}

func RegisterCartOrderServiceServer(s grpc.ServiceRegistrar, srv CartOrderServiceServer) {
	// If the following call pancis, it indicates UnimplementedCartOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CartOrderService_ServiceDesc, srv)
}

func _CartOrderService_ReserveCheckoutItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveCheckoutItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartOrderServiceServer).ReserveCheckoutItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartOrderService_ReserveCheckoutItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartOrderServiceServer).ReserveCheckoutItems(ctx, req.(*ReserveCheckoutItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartOrderService_GetCheckoutReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckoutReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartOrderServiceServer).GetCheckoutReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartOrderService_GetCheckoutReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartOrderServiceServer).GetCheckoutReservation(ctx, req.(*GetCheckoutReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartOrderService_CommitCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitCheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartOrderServiceServer).CommitCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartOrderService_CommitCheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartOrderServiceServer).CommitCheckout(ctx, req.(*CommitCheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CartOrderService_ReleaseCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseCheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartOrderServiceServer).ReleaseCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CartOrderService_ReleaseCheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartOrderServiceServer).ReleaseCheckout(ctx, req.(*ReleaseCheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CartOrderService_ServiceDesc is the grpc.ServiceDesc for CartOrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CartOrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.martketplace.vkr.cart.pkg.api.grpc.v1.order.CartOrderService",
	HandlerType: (*CartOrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReserveCheckoutItems",
			Handler:    _CartOrderService_ReserveCheckoutItems_Handler,
		},
		{
			MethodName: "GetCheckoutReservation",
			Handler:    _CartOrderService_GetCheckoutReservation_Handler,
		},
		{
			MethodName: "CommitCheckout",
			Handler:    _CartOrderService_CommitCheckout_Handler,
		},
		{
			MethodName: "ReleaseCheckout",
			Handler:    _CartOrderService_ReleaseCheckout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/order/cart_order_service.proto",
}
