// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: v1/client/cart_client_service.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Cart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*CartItem            `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Totals        *CartTotals            `protobuf:"bytes,4,opt,name=totals,proto3" json:"totals,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cart) Reset() {
	*x = Cart{}
	mi := &file_v1_client_cart_client_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_cart_client_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_v1_client_cart_client_service_proto_rawDescGZIP(), []int{0}
}

func (x *Cart) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Cart) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Cart) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Cart) GetTotals() *CartTotals {
	if x != nil {
		return x.Totals
	}
	return nil
}

func (x *Cart) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Cart) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CartItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductId         int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VendorId          int64                  `protobuf:"varint,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	VendorName        string                 `protobuf:"bytes,3,opt,name=vendor_name,json=vendorName,proto3" json:"vendor_name,omitempty"`
	ProductName       string                 `protobuf:"bytes,4,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	ImageUrl          string                 `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Quantity          uint32                 `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	AvailableQuantity uint32                 `protobuf:"varint,7,opt,name=available_quantity,json=availableQuantity,proto3" json:"available_quantity,omitempty"`
	Available         bool                   `protobuf:"varint,8,opt,name=available,proto3" json:"available,omitempty"`
	Selected          bool                   `protobuf:"varint,9,opt,name=selected,proto3" json:"selected,omitempty"`
	UnitPrice         string                 `protobuf:"bytes,10,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	TotalPrice        string                 `protobuf:"bytes,11,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	CurrencyId        int64                  `protobuf:"varint,12,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	RubPrice          string                 `protobuf:"bytes,13,opt,name=rub_price,json=rubPrice,proto3" json:"rub_price,omitempty"`
	UsdtPrice         string                 `protobuf:"bytes,14,opt,name=usdt_price,json=usdtPrice,proto3" json:"usdt_price,omitempty"`
	RubPerUsdt        string                 `protobuf:"bytes,15,opt,name=rub_per_usdt,json=rubPerUsdt,proto3" json:"rub_per_usdt,omitempty"`
	AcceptsCrypto     bool                   `protobuf:"varint,16,opt,name=accepts_crypto,json=acceptsCrypto,proto3" json:"accepts_crypto,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_v1_client_cart_client_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_cart_client_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_v1_client_cart_client_service_proto_rawDescGZIP(), []int{1}
}

func (x *CartItem) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CartItem) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *CartItem) GetVendorName() string {
	if x != nil {
		return x.VendorName
	}
	return ""
}

func (x *CartItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *CartItem) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CartItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CartItem) GetAvailableQuantity() uint32 {
	if x != nil {
		return x.AvailableQuantity
	}
	return 0
}

func (x *CartItem) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CartItem) GetSelected() bool {
	if x != nil {
		return x.Selected
	}
	return false
}

func (x *CartItem) GetUnitPrice() string {
	if x != nil {
		return x.UnitPrice
	}
	return ""
}

func (x *CartItem) GetTotalPrice() string {
	if x != nil {
		return x.TotalPrice
	}
	return ""
}

func (x *CartItem) GetCurrencyId() int64 {
	if x != nil {
		return x.CurrencyId
	}
	return 0
}

func (x *CartItem) GetRubPrice() string {
	if x != nil {
		return x.RubPrice
	}
	return ""
}

func (x *CartItem) GetUsdtPrice() string {
	if x != nil {
		return x.UsdtPrice
	}
	return ""
}

func (x *CartItem) GetRubPerUsdt() string {
	if x != nil {
		return x.RubPerUsdt
	}
	return ""
}

func (x *CartItem) GetAcceptsCrypto() bool {
	if x != nil {
		return x.AcceptsCrypto
	}
	return false
}

type CartTotals struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalItems    uint32                 `protobuf:"varint,1,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	Subtotal      string                 `protobuf:"bytes,2,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	Discount      string                 `protobuf:"bytes,3,opt,name=discount,proto3" json:"discount,omitempty"`
	Total         string                 `protobuf:"bytes,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartTotals) Reset() {
	*x = CartTotals{}
	mi := &file_v1_client_cart_client_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartTotals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartTotals) ProtoMessage() {}

func (x *CartTotals) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_cart_client_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartTotals.ProtoReflect.Descriptor instead.
func (*CartTotals) Descriptor() ([]byte, []int) {
	return file_v1_client_cart_client_service_proto_rawDescGZIP(), []int{2}
}

func (x *CartTotals) GetTotalItems() uint32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *CartTotals) GetSubtotal() string {
	if x != nil {
		return x.Subtotal
	}
	return ""
}

func (x *CartTotals) GetDiscount() string {
	if x != nil {
		return x.Discount
	}
	return ""
}

func (x *CartTotals) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_v1_client_cart_client_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_cart_client_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_cart_client_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetCartRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartResponse) Reset() {
	*x = GetCartResponse{}
	mi := &file_v1_client_cart_client_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartResponse) ProtoMessage() {}

func (x *GetCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_cart_client_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartResponse.ProtoReflect.Descriptor instead.
func (*GetCartResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_cart_client_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetCartResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VendorId      int64                  `protobuf:"varint,3,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	Quantity      uint32                 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_v1_client_cart_client_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_cart_client_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_cart_client_service_proto_rawDescGZIP(), []int{5}
}

func (x *AddItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddItemRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AddItemRequest) GetVendorId() int64 {
	if x != nil {
		return x.VendorId
	}
	return 0
}

func (x *AddItemRequest) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AddItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemResponse) Reset() {
	*x = AddItemResponse{}
	mi := &file_v1_client_cart_client_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemResponse) ProtoMessage() {}

func (x *AddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_cart_client_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemResponse.ProtoReflect.Descriptor instead.
func (*AddItemResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_cart_client_service_proto_rawDescGZIP(), []int{6}
}

func (x *AddItemResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type UpdateItemQuantityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      uint32                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemQuantityRequest) Reset() {
	*x = UpdateItemQuantityRequest{}
	mi := &file_v1_client_cart_client_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemQuantityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemQuantityRequest) ProtoMessage() {}

func (x *UpdateItemQuantityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_cart_client_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemQuantityRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemQuantityRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_cart_client_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateItemQuantityRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateItemQuantityRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateItemQuantityRequest) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateItemQuantityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemQuantityResponse) Reset() {
	*x = UpdateItemQuantityResponse{}
	mi := &file_v1_client_cart_client_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemQuantityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemQuantityResponse) ProtoMessage() {}

func (x *UpdateItemQuantityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_cart_client_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemQuantityResponse.ProtoReflect.Descriptor instead.
func (*UpdateItemQuantityResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_cart_client_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateItemQuantityResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type RemoveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemRequest) Reset() {
	*x = RemoveItemRequest{}
	mi := &file_v1_client_cart_client_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemRequest) ProtoMessage() {}

func (x *RemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_cart_client_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveItemRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_cart_client_service_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveItemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveItemRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type RemoveItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemResponse) Reset() {
	*x = RemoveItemResponse{}
	mi := &file_v1_client_cart_client_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemResponse) ProtoMessage() {}

func (x *RemoveItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_cart_client_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemResponse.ProtoReflect.Descriptor instead.
func (*RemoveItemResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_cart_client_service_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveItemResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type ClearCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartRequest) Reset() {
	*x = ClearCartRequest{}
	mi := &file_v1_client_cart_client_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartRequest) ProtoMessage() {}

func (x *ClearCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_cart_client_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartRequest.ProtoReflect.Descriptor instead.
func (*ClearCartRequest) Descriptor() ([]byte, []int) {
	return file_v1_client_cart_client_service_proto_rawDescGZIP(), []int{11}
}

func (x *ClearCartRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ClearCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cart          *Cart                  `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartResponse) Reset() {
	*x = ClearCartResponse{}
	mi := &file_v1_client_cart_client_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartResponse) ProtoMessage() {}

func (x *ClearCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_client_cart_client_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartResponse.ProtoReflect.Descriptor instead.
func (*ClearCartResponse) Descriptor() ([]byte, []int) {
	return file_v1_client_cart_client_service_proto_rawDescGZIP(), []int{12}
}

func (x *ClearCartResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

var File_v1_client_cart_client_service_proto protoreflect.FileDescriptor

const file_v1_client_cart_client_service_proto_rawDesc = "" +
	"\n" +
	"#v1/client/cart_client_service.proto\x127github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x02\n" +
	"\x04Cart\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12W\n" +
	"\x05items\x18\x03 \x03(\v2A.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartItemR\x05items\x12[\n" +
	"\x06totals\x18\x04 \x01(\v2C.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartTotalsR\x06totals\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x92\x04\n" +
	"\bCartItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1b\n" +
	"\tvendor_id\x18\x02 \x01(\x03R\bvendorId\x12\x1f\n" +
	"\vvendor_name\x18\x03 \x01(\tR\n" +
	"vendorName\x12!\n" +
	"\fproduct_name\x18\x04 \x01(\tR\vproductName\x12\x1b\n" +
	"\timage_url\x18\x05 \x01(\tR\bimageUrl\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\rR\bquantity\x12-\n" +
	"\x12available_quantity\x18\a \x01(\rR\x11availableQuantity\x12\x1c\n" +
	"\tavailable\x18\b \x01(\bR\tavailable\x12\x1a\n" +
	"\bselected\x18\t \x01(\bR\bselected\x12\x1d\n" +
	"\n" +
	"unit_price\x18\n" +
	" \x01(\tR\tunitPrice\x12\x1f\n" +
	"\vtotal_price\x18\v \x01(\tR\n" +
	"totalPrice\x12\x1f\n" +
	"\vcurrency_id\x18\f \x01(\x03R\n" +
	"currencyId\x12\x1b\n" +
	"\trub_price\x18\r \x01(\tR\brubPrice\x12\x1d\n" +
	"\n" +
	"usdt_price\x18\x0e \x01(\tR\tusdtPrice\x12 \n" +
	"\frub_per_usdt\x18\x0f \x01(\tR\n" +
	"rubPerUsdt\x12%\n" +
	"\x0eaccepts_crypto\x18\x10 \x01(\bR\racceptsCrypto\"{\n" +
	"\n" +
	"CartTotals\x12\x1f\n" +
	"\vtotal_items\x18\x01 \x01(\rR\n" +
	"totalItems\x12\x1a\n" +
	"\bsubtotal\x18\x02 \x01(\tR\bsubtotal\x12\x1a\n" +
	"\bdiscount\x18\x03 \x01(\tR\bdiscount\x12\x14\n" +
	"\x05total\x18\x04 \x01(\tR\x05total\")\n" +
	"\x0eGetCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"d\n" +
	"\x0fGetCartResponse\x12Q\n" +
	"\x04cart\x18\x01 \x01(\v2=.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartR\x04cart\"\x81\x01\n" +
	"\x0eAddItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x1b\n" +
	"\tvendor_id\x18\x03 \x01(\x03R\bvendorId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\rR\bquantity\"d\n" +
	"\x0fAddItemResponse\x12Q\n" +
	"\x04cart\x18\x01 \x01(\v2=.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartR\x04cart\"o\n" +
	"\x19UpdateItemQuantityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\rR\bquantity\"o\n" +
	"\x1aUpdateItemQuantityResponse\x12Q\n" +
	"\x04cart\x18\x01 \x01(\v2=.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartR\x04cart\"K\n" +
	"\x11RemoveItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\"g\n" +
	"\x12RemoveItemResponse\x12Q\n" +
	"\x04cart\x18\x01 \x01(\v2=.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartR\x04cart\"+\n" +
	"\x10ClearCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"f\n" +
	"\x11ClearCartResponse\x12Q\n" +
	"\x04cart\x18\x01 \x01(\v2=.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartR\x04cart2\xde\x06\n" +
	"\x11CartClientService\x12\x9c\x01\n" +
	"\aGetCart\x12G.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.GetCartRequest\x1aH.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.GetCartResponse\x12\x9c\x01\n" +
	"\aAddItem\x12G.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.AddItemRequest\x1aH.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.AddItemResponse\x12\xbd\x01\n" +
	"\x12UpdateItemQuantity\x12R.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.UpdateItemQuantityRequest\x1aS.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.UpdateItemQuantityResponse\x12\xa5\x01\n" +
	"\n" +
	"RemoveItem\x12J.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.RemoveItemRequest\x1aK.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.RemoveItemResponse\x12\xa2\x01\n" +
	"\tClearCart\x12I.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.ClearCartRequest\x1aJ.github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.ClearCartResponseB@Z>github.com/martketplace-vkr/cart/pkg/api/grpc/v1/client;clientb\x06proto3"

var (
	file_v1_client_cart_client_service_proto_rawDescOnce sync.Once
	file_v1_client_cart_client_service_proto_rawDescData []byte
)

func file_v1_client_cart_client_service_proto_rawDescGZIP() []byte {
	file_v1_client_cart_client_service_proto_rawDescOnce.Do(func() {
		file_v1_client_cart_client_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_client_cart_client_service_proto_rawDesc), len(file_v1_client_cart_client_service_proto_rawDesc)))
	})
	return file_v1_client_cart_client_service_proto_rawDescData
}

var file_v1_client_cart_client_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_v1_client_cart_client_service_proto_goTypes = []any{
	(*Cart)(nil),                       // 0: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.Cart
	(*CartItem)(nil),                   // 1: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartItem
	(*CartTotals)(nil),                 // 2: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartTotals
	(*GetCartRequest)(nil),             // 3: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.GetCartRequest
	(*GetCartResponse)(nil),            // 4: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.GetCartResponse
	(*AddItemRequest)(nil),             // 5: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.AddItemRequest
	(*AddItemResponse)(nil),            // 6: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.AddItemResponse
	(*UpdateItemQuantityRequest)(nil),  // 7: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.UpdateItemQuantityRequest
	(*UpdateItemQuantityResponse)(nil), // 8: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.UpdateItemQuantityResponse
	(*RemoveItemRequest)(nil),          // 9: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.RemoveItemRequest
	(*RemoveItemResponse)(nil),         // 10: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.RemoveItemResponse
	(*ClearCartRequest)(nil),           // 11: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.ClearCartRequest
	(*ClearCartResponse)(nil),          // 12: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.ClearCartResponse
	(*timestamppb.Timestamp)(nil),      // 13: google.protobuf.Timestamp
}
var file_v1_client_cart_client_service_proto_depIdxs = []int32{
	1,  // 0: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.Cart.items:type_name -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartItem
	2,  // 1: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.Cart.totals:type_name -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartTotals
	13, // 2: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.Cart.created_at:type_name -> google.protobuf.Timestamp
	13, // 3: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.Cart.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.GetCartResponse.cart:type_name -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.Cart
	0,  // 5: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.AddItemResponse.cart:type_name -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.Cart
	0,  // 6: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.UpdateItemQuantityResponse.cart:type_name -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.Cart
	0,  // 7: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.RemoveItemResponse.cart:type_name -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.Cart
	0,  // 8: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.ClearCartResponse.cart:type_name -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.Cart
	3,  // 9: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartClientService.GetCart:input_type -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.GetCartRequest
	5,  // 10: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartClientService.AddItem:input_type -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.AddItemRequest
	7,  // 11: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartClientService.UpdateItemQuantity:input_type -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.UpdateItemQuantityRequest
	9,  // 12: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartClientService.RemoveItem:input_type -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.RemoveItemRequest
	11, // 13: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartClientService.ClearCart:input_type -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.ClearCartRequest
	4,  // 14: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartClientService.GetCart:output_type -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.GetCartResponse
	6,  // 15: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartClientService.AddItem:output_type -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.AddItemResponse
	8,  // 16: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartClientService.UpdateItemQuantity:output_type -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.UpdateItemQuantityResponse
	10, // 17: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartClientService.RemoveItem:output_type -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.RemoveItemResponse
	12, // 18: github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.CartClientService.ClearCart:output_type -> github.com.martketplace.vkr.cart.pkg.api.grpc.v1.client.ClearCartResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_v1_client_cart_client_service_proto_init() }
func file_v1_client_cart_client_service_proto_init() {
	if File_v1_client_cart_client_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_client_cart_client_service_proto_rawDesc), len(file_v1_client_cart_client_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_client_cart_client_service_proto_goTypes,
		DependencyIndexes: file_v1_client_cart_client_service_proto_depIdxs,
		MessageInfos:      file_v1_client_cart_client_service_proto_msgTypes,
	}.Build()
	File_v1_client_cart_client_service_proto = out.File
	file_v1_client_cart_client_service_proto_goTypes = nil
	file_v1_client_cart_client_service_proto_depIdxs = nil
}
